# Data Preparation

In [14]:
# Raw Dataset

In [ ]:
import pandas as pd
import json
import glob

cloudtrail_folder = os.path.expanduser("~/Desktop/Pre Thesis/Dataset/Raw/CloudTrail/*.json")

records = []

print("Loading CloudTrail logs...")

for file in glob.glob(cloudtrail_folder):
    with open(file, "r") as f:
        data = json.load(f)

        # Extract records safely
        if "Records" in data:
            records.extend(data["Records"])

print("Total raw records:", len(records))

df_identity = pd.DataFrame(records)

# limit to 1000 rows for now
df_identity = df_identity.head(1000)

print("Data loaded successfully")
print("Shape:", df_identity.shape)

Loading CloudTrail logs...
Total raw records: 2900
Data loaded successfully
Shape: (1000, 27)

## Data Inspection

In [22]:
print(df_identity.columns)

Index(['eventVersion', 'userIdentity', 'eventTime', 'eventSource', 'eventName',
       'awsRegion', 'sourceIPAddress', 'userAgent', 'requestParameters',
       'responseElements', 'additionalEventData', 'requestID', 'eventID',
       'readOnly', 'eventType', 'managementEvent', 'recipientAccountId',
       'eventCategory', 'resources', 'vpcEndpointId', 'tlsDetails',
       'errorCode', 'errorMessage', 'apiVersion',
       'sessionCredentialFromConsole', 'sharedEventID', 'serviceEventDetails'],
      dtype='object')

In [23]:
df_identity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   eventVersion                  1000 non-null   object
 1   userIdentity                  1000 non-null   object
 2   eventTime                     1000 non-null   object
 3   eventSource                   1000 non-null   object
 4   eventName                     1000 non-null   object
 5   awsRegion                     1000 non-null   object
 6   sourceIPAddress               1000 non-null   object
 7   userAgent                     1000 non-null   object
 8   requestParameters             931 non-null    object
 9   responseElements              135 non-null    object
 10  additionalEventData           105 non-null    object
 11  requestID                     999 non-null    object
 12  eventID                       1000 non-null   object
 13  readOnly                      1000 non-null   bool
 14  eventType                     1000 non-null   object
 15  managementEvent               1000 non-null   bool
 16  recipientAccountId            1000 non-null   object
 17  eventCategory                 1000 non-null   object
 18  resources                     384 non-null    object
 19  vpcEndpointId                 97 non-null     object
 20  tlsDetails                    787 non-null    object
 21  errorCode                     114 non-null    object
 22  errorMessage                  113 non-null    object
 23  apiVersion                    4 non-null      object
 24  sessionCredentialFromConsole  10 non-null     object
 25  sharedEventID                 9 non-null      object
 26  serviceEventDetails           1 non-null      object
dtypes: bool(2), object(25)
memory usage: 197.4+ KB

In [ ]:
# userIdentity         object
# requestParameters    object
# resources            object
# additionalEventData  object

# These must be flattened.

In [24]:
df_identity[['eventTime','eventSource','eventName','sourceIPAddress']].head()

,eventTime,eventSource,eventName,sourceIPAddress
0,2023-07-10T11:42:36Z,s3.amazonaws.com,GetStorageLensConfiguration,AWS Internal
1,2023-07-10T11:42:44Z,s3.amazonaws.com,GetBucketPublicAccessBlock,10.248.16.43
2,2023-07-10T11:42:44Z,s3.amazonaws.com,GetBucketPolicyStatus,10.248.16.43
3,2023-07-10T11:42:44Z,s3.amazonaws.com,GetBucketAcl,10.248.16.43
4,2023-07-10T11:42:44Z,s3.amazonaws.com,GetBucketPublicAccessBlock,10.248.16.43

In [25]:
df_identity['userIdentity'].iloc[0]

{'type': 'IAMUser',
 'principalId': 'AIDATFQR7NSC5U6Q3TMDR',
 'arn': 'arn:aws:iam::123837392027:user/benjamin',
 'accountId': '123837392027',
 'accessKeyId': 'ASIATFQR7NSCTM3XVF6B',
 'userName': 'benjamin',
 'sessionContext': {'sessionIssuer': {},
  'webIdFederationData': {},
  'attributes': {'creationDate': '2023-07-10T11:42:31Z',
   'mfaAuthenticated': 'true'}},
 'invokedBy': 'AWS Internal'}

## Flatten userIdentity

In [ ]:
# The column userIdentity contains a dictionary like:

# {
#  'type': 'IAMUser',
#  'principalId': 'AID...',
#  'arn': 'arn:aws:iam::...',
#  'accountId': '...',
#  'accessKeyId': '...',
#  'userName': 'benjamin',
#  'sessionContext': {...},
#  'invokedBy': 'AWS Internal'
# }

# Dictionary is a nested column. Machine learning models cannot use dictionaries, so we need to flatten them into normal columns.

In [26]:
# Convert nested JSON to columns
user_identity_df = pd.json_normalize(df_identity['userIdentity'])

# Show the new columns
print(user_identity_df.columns)

Index(['type', 'principalId', 'arn', 'accountId', 'accessKeyId', 'userName',
       'invokedBy', 'sessionContext.attributes.creationDate',
       'sessionContext.attributes.mfaAuthenticated',
       'sessionContext.sessionIssuer.type',
       'sessionContext.sessionIssuer.principalId',
       'sessionContext.sessionIssuer.arn',
       'sessionContext.sessionIssuer.accountId',
       'sessionContext.sessionIssuer.userName',
       'sessionContext.ec2RoleDelivery'],
      dtype='object')

In [27]:
df_identity = pd.concat([df_identity, user_identity_df], axis=1)

In [28]:
df_identity.drop(columns=['userIdentity'], inplace=True)

In [31]:
df_identity.shape

(1000, 41)

In [32]:
df_identity[['userName','type','invokedBy']].head()

   userName     type     invokedBy
0  benjamin  IAMUser  AWS Internal
1  benjamin  IAMUser           NaN
2  benjamin  IAMUser           NaN
3  benjamin  IAMUser           NaN
4  benjamin  IAMUser           NaN

In [29]:
df_identity.columns

Index(['eventVersion', 'eventTime', 'eventSource', 'eventName', 'awsRegion',
       'sourceIPAddress', 'userAgent', 'requestParameters', 'responseElements',
       'additionalEventData', 'requestID', 'eventID', 'readOnly', 'eventType',
       'managementEvent', 'recipientAccountId', 'eventCategory', 'resources',
       'vpcEndpointId', 'tlsDetails', 'errorCode', 'errorMessage',
       'apiVersion', 'sessionCredentialFromConsole', 'sharedEventID',
       'serviceEventDetails', 'type', 'principalId', 'arn', 'accountId',
       'accessKeyId', 'userName', 'invokedBy',
       'sessionContext.attributes.creationDate',
       'sessionContext.attributes.mfaAuthenticated',
       'sessionContext.sessionIssuer.type',
       'sessionContext.sessionIssuer.principalId',
       'sessionContext.sessionIssuer.arn',
       'sessionContext.sessionIssuer.accountId',
       'sessionContext.sessionIssuer.userName',
       'sessionContext.ec2RoleDelivery'],
      dtype='object')

## Handle Missing Values in Identity Fields

In [33]:
missing = df_identity.isnull().sum().sort_values(ascending=False)
missing_percent = (missing / len(df_identity)) * 100

missing_table = pd.concat([missing, missing_percent], axis=1)
missing_table.columns = ["Missing Count", "Missing %"]

missing_table.head(15)

                                          Missing Count  Missing %
serviceEventDetails                                 999       99.9
apiVersion                                          996       99.6
sharedEventID                                       991       99.1
sessionCredentialFromConsole                        990       99.0
sessionContext.ec2RoleDelivery                      986       98.6
sessionContext.sessionIssuer.type                   939       93.9
sessionContext.sessionIssuer.arn                    939       93.9
sessionContext.sessionIssuer.userName               939       93.9
sessionContext.sessionIssuer.accountId              939       93.9
sessionContext.sessionIssuer.principalId            939       93.9
vpcEndpointId                                       903       90.3
additionalEventData                                 895       89.5
errorMessage                                        887       88.7
errorCode                                           886       88.6
responseElements                                    865       86.5

In [34]:
identity_cols = [
    'type',
    'principalId',
    'accountId',
    'accessKeyId',
    'userName',
    'invokedBy',
    'sessionContext.attributes.mfaAuthenticated',
    'sessionContext.sessionIssuer.type',
    'sessionContext.sessionIssuer.userName'
]

df_identity[identity_cols].isnull().sum()

type                                            1
principalId                                     9
accountId                                       8
accessKeyId                                    11
userName                                       70
invokedBy                                     795
sessionContext.attributes.mfaAuthenticated    704
sessionContext.sessionIssuer.type             939
sessionContext.sessionIssuer.userName         939
dtype: int64

In [ ]:
# Create new col only for identity field - to avoid noise

identity_cols = [
    'type',
    'principalId',
    'accountId',
    'accessKeyId',
    'userName',
    'invokedBy',
    'sessionContext.attributes.mfaAuthenticated',
    'sessionContext.sessionIssuer.type',
    'sessionContext.sessionIssuer.userName'
]

df_identity[identity_cols].isnull().sum()

In [36]:
df_identity[identity_cols] = df_identity[identity_cols].fillna("Unknown")

In [37]:
df_identity[identity_cols].isnull().sum()

type                                          0
principalId                                   0
accountId                                     0
accessKeyId                                   0
userName                                      0
invokedBy                                     0
sessionContext.attributes.mfaAuthenticated    0
sessionContext.sessionIssuer.type             0
sessionContext.sessionIssuer.userName         0
dtype: int64

When detecting anomalies in cloud access logs, missing values can represent important behaviors. Replacing NaN with "Unknown" preserves the signal instead of deleting it.

In [38]:
missing_table.head(10)

                                          Missing Count  Missing %
serviceEventDetails                                 999       99.9
apiVersion                                          996       99.6
sharedEventID                                       991       99.1
sessionCredentialFromConsole                        990       99.0
sessionContext.ec2RoleDelivery                      986       98.6
sessionContext.sessionIssuer.type                   939       93.9
sessionContext.sessionIssuer.arn                    939       93.9
sessionContext.sessionIssuer.userName               939       93.9
sessionContext.sessionIssuer.accountId              939       93.9
sessionContext.sessionIssuer.principalId            939       93.9

In [39]:
df_identity[identity_cols].isnull().sum()

type                                          0
principalId                                   0
accountId                                     0
accessKeyId                                   0
userName                                      0
invokedBy                                     0
sessionContext.attributes.mfaAuthenticated    0
sessionContext.sessionIssuer.type             0
sessionContext.sessionIssuer.userName         0
dtype: int64

## Extract Time Features from eventTime

In [ ]:
# Attackers often behave differently in time patterns:

# Examples:
# Access at 03:00 AM
# Access during weekends
# Unusual burst activity

# We will convert eventTime into useful features.

In [60]:
# Convert to date and time

df_identity['eventTime'] = pd.to_datetime(df_identity['eventTime'])
df_identity['eventTime'].head(1000)

0     2023-07-10 11:42:36+00:00
1     2023-07-10 11:42:44+00:00
2     2023-07-10 11:42:44+00:00
3     2023-07-10 11:42:44+00:00
4     2023-07-10 11:42:44+00:00
                 ...
995   2023-07-10 12:05:08+00:00
996   2023-07-10 12:05:08+00:00
997   2023-07-10 12:05:11+00:00
998   2023-07-10 12:05:10+00:00
999   2023-07-10 12:05:15+00:00
Name: eventTime, Length: 1000, dtype: datetime64[ns, UTC]

In [47]:
# Extract hour

df_identity['event_hour'] = df_identity['eventTime'].dt.hour
df_identity['event_hour'].head()

0    11
1    11
2    11
3    11
4    11
Name: event_hour, dtype: int32

In [51]:
# Extract day of the week

df_identity['event_dayofweek'] = df_identity['eventTime'].dt.dayofweek
df_identity['event_dayofweek'].head()

0    0
1    0
2    0
3    0
4    0
Name: event_dayofweek, dtype: int32

In [53]:
# Extract date

df_identity['event_date'] = df_identity['eventTime'].dt.date
df_identity['event_date'].head()

0    2023-07-10
1    2023-07-10
2    2023-07-10
3    2023-07-10
4    2023-07-10
Name: event_date, dtype: object

In [55]:
# Detect Weekend Activity

df_identity['is_weekend'] = df_identity['event_dayofweek'].isin([5,6]).astype(int)
df_identity['is_weekend'].head()

0    0
1    0
2    0
3    0
4    0
Name: is_weekend, dtype: int64